"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { isAdmin } from "../_lib/auth";
import { sql } from "../_lib/db";
const value=(f:FormData,k:string)=>String(f.get(k)??"").trim();
async function admin(){if(!await isAdmin())redirect("/login")}
function done(message:string){revalidatePath("/");revalidatePath("/dashboard");redirect(`/dashboard?toast=${encodeURIComponent(message)}`)}
export async function saveCategory(f:FormData){await admin();const slug=value(f,"slug"),name=value(f,"name");if(!slug||!name)done("أكمل بيانات القسم.");const db=sql();await db`ALTER TABLE categories ADD COLUMN IF NOT EXISTS image_url TEXT`;await db`INSERT INTO categories (slug,name,description,parent_slug,glyph,color,image_url,active) VALUES (${slug},${name},${value(f,"description")||name},${value(f,"parent_slug")||null},'✦','from-[#103cff] to-[#6e82ff]',${value(f,"image_url")||null},true) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,parent_slug=EXCLUDED.parent_slug,image_url=EXCLUDED.image_url,active=true`;done("تم حفظ القسم بنجاح.")}
export async function removeCategory(f:FormData){await admin();const db=sql(),slug=value(f,"slug");await db`UPDATE categories SET parent_slug=NULL WHERE parent_slug=${slug}`;await db`UPDATE categories SET active=false WHERE slug=${slug}`;done("تم حذف القسم من المتجر.")}
export async function saveProduct(f:FormData){await admin();const slug=value(f,"slug"),name=value(f,"name"),category=value(f,"category_slug"),price=Number(value(f,"price"));if(!slug||!name||!category||!Number.isFinite(price))done("أكمل بيانات المنتج المطلوبة.");await sql()`INSERT INTO products (slug,name,category_slug,price_usd,note,glyph,color,duration,delivery,account_type,featured,active) VALUES (${slug},${name},${category},${price},${value(f,"note")||name},'✦','from-[#103cff] to-[#6e82ff]',${value(f,"duration")||'شهر كامل'},${value(f,"delivery")||'خلال 15 دقيقة'},${value(f,"account_type")||'تفعيل مضمون'},${f.get("featured")==='on'},true) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name,category_slug=EXCLUDED.category_slug,price_usd=EXCLUDED.price_usd,note=EXCLUDED.note,duration=EXCLUDED.duration,delivery=EXCLUDED.delivery,account_type=EXCLUDED.account_type,featured=EXCLUDED.featured,active=true,updated_at=now()`;done("تم حفظ المنتج بنجاح.")}
export async function removeProduct(f:FormData){await admin();await sql()`UPDATE products SET active=false WHERE slug=${value(f,"slug")}`;done("تم حذف المنتج من المتجر.")}
export async function updateRate(f:FormData){await admin();const rate=Number(value(f,"rate"));if(!Number.isFinite(rate)||rate<=0)done("أدخل سعر صرف صحيح.");await sql()`INSERT INTO store_settings(key,value) VALUES('exchange_rate',${String(rate)}) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_at=now()`;done("تم تحديث سعر الصرف.")}
