import { redirect } from "next/navigation";
import { isAdmin } from "../_lib/auth";
import { sql } from "../_lib/db";
import { addCategory, addProduct, updateRate } from "./actions";
import { logout } from "../login/actions";

export default async function Dashboard(){
  if(!await isAdmin())redirect("/login"); const db=sql(); const [categories,products,rate]=await Promise.all([db`SELECT slug,name FROM categories WHERE active=true ORDER BY name`,db`SELECT slug,name,price_usd FROM products WHERE active=true ORDER BY created_at DESC`,db`SELECT value FROM store_settings WHERE key='exchange_rate'`]); const input="w-full rounded-xl border border-black/10 px-3 py-2 text-sm";
  return <main className="min-h-screen bg-[#f8f9fc] p-5 text-[#101114]"><div className="mx-auto max-w-5xl"><header className="flex justify-between"><div><p className="font-black text-[#103cff]">Raeed Dev</p><h1 className="mt-2 text-3xl font-black">لوحة الإدارة</h1></div><form action={logout}><button className="rounded-xl border px-4 py-2">خروج</button></form></header><div className="mt-8 grid gap-5 md:grid-cols-2"><form action={addCategory} className="space-y-3 rounded-3xl bg-white p-6"><h2 className="text-xl font-black">إضافة قسم</h2><input className={input} name="name" placeholder="اسم القسم" required/><input className={input} name="slug" placeholder="slug مثال: ai" required/><input className={input} name="description" placeholder="وصف القسم"/><button className="rounded-xl bg-[#103cff] px-4 py-2 text-white">حفظ القسم</button></form><form action={updateRate} className="space-y-3 rounded-3xl bg-white p-6"><h2 className="text-xl font-black">سعر الصرف</h2><input className={input} name="rate" defaultValue={rate[0]?.value??"1350"}/><button className="rounded-xl bg-[#103cff] px-4 py-2 text-white">حفظ السعر</button></form><form action={addProduct} className="space-y-3 rounded-3xl bg-white p-6 md:col-span-2"><h2 className="text-xl font-black">إضافة أو تعديل منتج</h2><div className="grid gap-3 sm:grid-cols-2"><input className={input} name="name" placeholder="اسم المنتج" required/><input className={input} name="slug" placeholder="slug مثال: canva-pro" required/><select className={input} name="category" required><option value="">اختر القسم</option>{categories.map(c=><option key={c.slug} value={c.slug}>{c.name}</option>)}</select><input className={input} name="price" type="number" step="0.01" placeholder="السعر بالدولار" required/><input className={input} name="duration" placeholder="المدة"/><input className={input} name="delivery" placeholder="وقت التفعيل"/><input className={input} name="type" placeholder="نوع الخدمة"/><input className={input} name="note" placeholder="وصف المنتج"/></div><label className="text-sm"><input name="featured" type="checkbox"/> منتج مميز</label><button className="block rounded-xl bg-[#103cff] px-4 py-2 text-white">حفظ المنتج</button></form></div><section className="mt-6 rounded-3xl bg-white p-6"><h2 className="text-xl font-black">المنتجات</h2><div className="mt-4 space-y-2">{products.map(p=><div key={p.slug} className="flex justify-between rounded-xl bg-black/[.03] p-3"><b>{p.name}</b><span>${p.price_usd}</span></div>)}</div></section></div></main>;
}
